version: '3.8'

services:
  eshobdb:
    environment:
      TZ: UTC
    ports:
      - "1433:1433"

  seq:
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:5341"
      - "9091:80"
    volumes:
      - seq-data:/data
    restart: unless-stopped

volumes:
  seq-data: